In [1]:
import MLM.moire_lattice_vector_finder as mlf
import numpy as np
import pandas as pd
import time
import sys, os
from pprint import pprint

sys.path.append("../AtomLayers/refactor")

In [2]:
from match import run_and_filter

In [3]:
file_1 = "../moire_structures/bto/bto_1-layer.vasp"
file_2 = "../moire_structures/bto/bto_1-layer.vasp"

In [4]:
lattice_vectors1, atom_type_arr1, dat1 = mlf.read_vasp(file_1)

In [5]:
lattice_vectors1['a']

array([3.9903791, 0.       , 0.       ])

In [6]:
lattice_vectors2, atom_type_arr2, dat2 = mlf.read_vasp(file_2)

In [7]:
mlf.angle_between(lattice_vectors1['a'],lattice_vectors1['b'])

90.0

In [8]:
results = run_and_filter(a1=lattice_vectors1['a'][0:2],a2=lattice_vectors1['b'][0:2],
                      g1=lattice_vectors2['a'][0:2],g2=lattice_vectors2['b'][0:2],
                      degmin=1, degmax = 45.01, degstep = 0.01,
                      dtol = 1e-3, nmin = -20, nmax = 20, goodangles = [90.0])

In [9]:
angle=[]
A1 = []
A2 = []
delvec = []
delgood = []
norm_A1 = []
norm_A2 = []
#num_atoms_app = []

for result in results[0]['results']:
    # pprint(len(result))
    # pprint(result)
    # pprint("#################")
    # pprint(result[0]['angle'])
    angle.append(result[0]['angle'])
    # pprint(result[0]['matchpoint'])
    A1.append(result[0]['matchpoint'])
    # pprint(result[1]['matchpoint'])
    A2.append(result[1]['matchpoint'])
    # pprint(result[2]['delgoodangle'])
    delvec.append(result[0]['delvec'])
    delgood.append(np.abs(result[2]['delgoodangle']))
    norm_A1.append(np.linalg.norm(np.array(result[0]['matchpoint'])))
    norm_A2.append(np.linalg.norm(np.array(result[1]['matchpoint'])))
    #num_atoms_app.append(np.abs(density * np.cross(np.array(result[0]['matchpoint']), np.array(result[1]['matchpoint']))))
    
    
    # break

In [10]:
resdf = pd.DataFrame(zip(angle,A1,A2,delvec,delgood,norm_A1, norm_A2), columns=['Theta','A1', 'A2', 'delvec', 'delang','norm_A1', 'norm_A2'])

In [11]:
len(resdf)

2102

In [26]:
# Sort the DataFrame by 'degree' in ascending order and 'norm' in descending order, followed by 'vec_del' and 'delta_angle'
rsdf_sorted = resdf.sort_values(by=['Theta', 'delvec', 'norm_A1'], ascending=[True, True, True])

In [27]:
rsdf_sorted.head(60)

,Theta,A1,A2,delvec,delang,norm_A1,norm_A2
0,2.94,"[-79.80758190200001, 75.8172028069]","[-75.8172028069, -79.80758190200001]",0.004608,0.0,110.079509,110.079509
1,2.94,"[-75.8172028069, -79.80758190200001]","[-79.80758190200001, 75.8172028069]",0.004608,0.0,110.079509,110.079509
2,3.27,"[-71.8268237118, 67.8364446167]","[-67.8364446167, -71.8268237118]",0.005439,0.0,98.797145,98.797145
3,3.27,"[-71.8268237118, 67.8364446167]","[67.8364446167, 71.8268237118]",0.005439,0.0,98.797145,98.797145
4,3.27,"[-67.8364446167, -71.8268237118]","[-71.8268237118, 67.8364446167]",0.005439,0.0,98.797145,98.797145
5,3.27,"[-67.8364446167, -71.8268237118]","[71.8268237118, -67.8364446167]",0.005439,0.0,98.797145,98.797145
6,3.27,"[67.8364446167, 71.8268237118]","[-71.8268237118, 67.8364446167]",0.005439,0.0,98.797145,98.797145
7,3.27,"[67.8364446167, 71.8268237118]","[71.8268237118, -67.8364446167]",0.005439,0.0,98.797145,98.797145
8,3.27,"[71.8268237118, -67.8364446167]","[-67.8364446167, -71.8268237118]",0.005439,0.0,98.797145,98.797145
9,3.27,"[71.8268237118, -67.8364446167]","[67.8364446167, 71.8268237118]",0.005439,0.0,98.797145,98.797145
12,3.47,"[-63.8460655216, -67.8364446167]","[-67.8364446167, 63.8460655216]",0.002291,0.0,93.156338,93.156338
13,3.47,"[-63.8460655216, -67.8364446167]","[67.8364446167, -63.8460655216]",0.002291,0.0,93.156338,93.156338
14,3.47,"[63.8460655216, 67.8364446167]","[-67.8364446167, 63.8460655216]",0.002291,0.0,93.156338,93.156338
15,3.47,"[63.8460655216, 67.8364446167]","[67.8364446167, -63.8460655216]",0.002291,0.0,93.156338,93.156338
10,3.47,"[-67.8364446167, 63.8460655216]","[-63.8460655216, -67.8364446167]",0.002291,0.0,93.156338,93.156338
11,3.47,"[-67.8364446167, 63.8460655216]","[63.8460655216, 67.8364446167]",0.002291,0.0,93.156338,93.156338
16,3.47,"[67.8364446167, -63.8460655216]","[-63.8460655216, -67.8364446167]",0.002291,0.0,93.156338,93.156338
17,3.47,"[67.8364446167, -63.8460655216]","[63.8460655216, 67.8364446167]",0.002291,0.0,93.156338,93.156338
20,3.95,"[-55.865307331400004, -59.8556864265]","[-59.8556864265, 55.865307331400004]",0.000189,0.0,81.875734,81.875734
21,3.95,"[-55.865307331400004, -59.8556864265]","[59.8556864265, -55.865307331400004]",0.000189,0.0,81.875734,81.875734
22,3.95,"[55.865307331400004, 59.8556864265]","[-59.8556864265, 55.865307331400004]",0.000189,0.0,81.875734,81.875734
23,3.95,"[55.865307331400004, 59.8556864265]","[59.8556864265, -55.865307331400004]",0.000189,0.0,81.875734,81.875734
18,3.95,"[-59.8556864265, 55.865307331400004]","[-55.865307331400004, -59.8556864265]",0.000189,0.0,81.875734,81.875734
19,3.95,"[-59.8556864265, 55.865307331400004]","[55.865307331400004, 59.8556864265]",0.000189,0.0,81.875734,81.875734
24,3.95,"[59.8556864265, -55.865307331400004]","[-55.865307331400004, -59.8556864265]",0.000189,0.0,81.875734,81.875734
25,3.95,"[59.8556864265, -55.865307331400004]","[55.865307331400004, 59.8556864265]",0.000189,0.0,81.875734,81.875734
26,4.24,"[-55.865307331400004, 51.8749282363]","[-51.8749282363, -55.865307331400004]",0.002918,0.0,76.236086,76.236086
27,4.24,"[-55.865307331400004, 51.8749282363]","[51.8749282363, 55.865307331400004]",0.002918,0.0,76.236086,76.236086
32,4.24,"[55.865307331400004, -51.8749282363]","[-51.8749282363, -55.865307331400004]",0.002918,0.0,76.236086,76.236086
33,4.24,"[55.865307331400004, -51.8749282363]","[51.8749282363, 55.865307331400004]",0.002918,0.0,76.236086,76.236086
28,4.24,"[-51.8749282363, -55.865307331400004]","[-55.865307331400004, 51.8749282363]",0.002918,0.0,76.236086,76.236086
29,4.24,"[-51.8749282363, -55.865307331400004]","[55.865307331400004, -51.8749282363]",0.002918,0.0,76.236086,76.236086
30,4.24,"[51.8749282363, 55.865307331400004]","[-55.865307331400004, 51.8749282363]",0.002918,0.0,76.236086,76.236086
31,4.24,"[51.8749282363, 55.865307331400004]","[55.865307331400004, -51.8749282363]",0.002918,0.0,76.236086,76.236086
34,4.58,"[-51.8749282363, 47.884549141200004]","[-47.884549141200004, -51.8749282363]",0.001503,0.0,70.597013,70.597013
35,4.58,"[-51.8749282363, 47.884549141200004]","[47.884549141200004, 51.8749282363]",0.001503,0.0,70.597013,70.597013
40,4.58,"[51.8749282363, -47.884549141200004]","[-47.884549141200004, -51.8749282363]",0.001503,0.0,70.597013,70.597013
41,4.58,"[51.8749282363, -47.884549141200004]","[47.884549141200004, 51.8749282363]",0.001503,0.0,70.597013,70.597013
36,4.58,"[-47.884549141200004, -51.8749282363]","[-51.8749282363, 47.884549141200004]",0.001503,0.0,70.597013,70.597013
37,4.58,"[-47.884549141200004, -51.8749282363]","[51.8749282363, -47.884549141200004]",0.001503,0.0,70.597013,70.597013
38,4.58,"[47.884549141200004, 51.8749282363]","[-51.8749282363, 47.884549141200004]",0.001503,0.0,70.597013,70.597013
39,4.58,"[47.884549141200004, 51.8749282363]","[51.8749282363, -47.884549141200004]",0.001503,0.0,70.597013,70.597013
42,4.98,"[-47.884549141200004, 43.8941700461]","[-43.8941700461, -47.884549141200004]",0.001014,0.0,64.958665,64.958665
43,4.98,"[-47.884549141200004, 43.8941700461]","[43.8941700461, 47.884549141200004]",0.001014,0.0,64.958665,64.958665
44,4.98,"[-43.8941700461, -47.884549141200004]","[-47.884549141200004, 43.8941700461]",0.001014,0.0,64.958665,64.958665
45,4.98,"[-43.8941700461, -47.884549141200004]","[47.884549141200004, -43.8941700461]",0.001014,0.0,64.958665,64.958665
46,4.98,"[43.8941700461, 47.884549141200004]","[-47.884549141200004, 43.8941700461]",0.001014,0.0,64.958665,64.958665
47,4.98,"[43.8941700461, 47.884549141200004]","[47.884549141200004, -43.8941700461]",0.001014,0.0,64.958665,64.958665
48,4.98,"[47.884549141200004, -43.8941700461]","[-43.8941700461, -47.884549141200004]",0.001014,0.0,64.958665,64.958665
49,4.98,"[47.884549141200004, -43.8941700461]","[43.8941700461, 47.884549141200004]",0.001014,0.0,64.958665,64.958665
50,5.45,"[-43.8941700461, 39.903790951000005]","[-39.903790951000005, -43.8941700461]",0.002715,0.0,59.321250,59.321250
51,5.45,"[-43.8941700461, 39.903790951000005]","[39.903790951000005, 43.8941700461]",0.002715,0.0,59.321250,59.321250
52,5.45,"[-39.903790951000005, -43.8941700461]","[-43.8941700461, 39.903790951000005]",0.002715,0.0,59.321250,59.321250
53,5.45,"[-39.903790951000005, -43.8941700461]","[43.8941700461, -39.903790951000005]",0.002715,0.0,59.321250,59.321250
54,5.45,"[39.903790951000005, 43.8941700461]","[-43.8941700461, 39.903790951000005]",0.002715,0.0,59.321250,59.321250
55,5.45,"[39.903790951000005, 43.8941700461]","[43.8941700461, -39.903790951000005]",0.002715,0.0,59.321250,59.321250
56,5.45,"[43.8941700461, -39.903790951000005]","[-39.903790951000005, -43.8941700461]",0.002715,0.0,59.321250,59.321250
57,5.45,"[43.8941700461, -39.903790951000005]","[39.903790951000005, 43.8941700461]",0.002715,0.0,59.321250,59.321250
58,6.02,"[-39.903790951000005, 35.9134118559]","[-35.9134118559, -39.903790951000005]",0.005224,0.0,53.685060,53.685060
59,6.02,"[-39.903790951000005, 35.9134118559]","[35.9134118559, 39.903790951000005]",0.005224,0.0,53.685060,53.685060

In [28]:
# Group by 'degree' and take the first entry in each group
final_rsdf = rsdf_sorted.groupby('Theta', as_index=False).first()

In [29]:
len(final_rsdf)

92

In [30]:
# final_rsdf['num_atoms'] = np.round(1.574158*final_rsdf['norm_A1']*final_rsdf['norm_A2'])

In [31]:
final_rsdf.sort_values(by="Theta", ascending=True).head(60)

,Theta,A1,A2,delvec,delang,norm_A1,norm_A2
0,2.94,"[-79.80758190200001, 75.8172028069]","[-75.8172028069, -79.80758190200001]",0.004608,0.0,110.079509,110.079509
1,3.27,"[-71.8268237118, 67.8364446167]","[-67.8364446167, -71.8268237118]",0.005439,0.0,98.797145,98.797145
2,3.47,"[-63.8460655216, -67.8364446167]","[-67.8364446167, 63.8460655216]",0.002291,0.0,93.156338,93.156338
3,3.95,"[-55.865307331400004, -59.8556864265]","[-59.8556864265, 55.865307331400004]",0.000189,0.0,81.875734,81.875734
4,4.24,"[-55.865307331400004, 51.8749282363]","[-51.8749282363, -55.865307331400004]",0.002918,0.0,76.236086,76.236086
5,4.58,"[-51.8749282363, 47.884549141200004]","[-47.884549141200004, -51.8749282363]",0.001503,0.0,70.597013,70.597013
6,4.98,"[-47.884549141200004, 43.8941700461]","[-43.8941700461, -47.884549141200004]",0.001014,0.0,64.958665,64.958665
7,5.45,"[-43.8941700461, 39.903790951000005]","[-39.903790951000005, -43.8941700461]",0.002715,0.0,59.321250,59.321250
8,6.02,"[-39.903790951000005, 35.9134118559]","[-35.9134118559, -39.903790951000005]",0.005224,0.0,53.685060,53.685060
9,6.03,"[-39.903790951000005, 35.9134118559]","[-35.9134118559, -39.903790951000005]",0.004146,0.0,53.685060,53.685060
10,6.36,"[-71.8268237118, -3.9903790951]","[-3.9903790951, 71.8268237118]",0.000427,0.0,71.937582,71.937582
11,6.73,"[-35.9134118559, 31.9230327608]","[-31.9230327608, -35.9134118559]",0.002450,0.0,48.050527,48.050527
12,7.15,"[-63.8460655216, -3.9903790951]","[-3.9903790951, 63.8460655216]",0.002980,0.0,63.970643,63.970643
13,7.63,"[-31.9230327608, 27.932653665700002]","[-27.932653665700002, -31.9230327608]",0.001370,0.0,42.418312,42.418312
14,8.17,"[-55.865307331400004, -3.9903790951]","[-3.9903790951, 55.865307331400004]",0.001206,0.0,56.007640,56.007640
15,8.79,"[-23.942274570600002, -27.932653665700002]","[-27.932653665700002, 23.942274570600002]",0.004758,0.0,36.789477,36.789477
16,8.80,"[-27.932653665700002, 23.942274570600002]","[-23.942274570600002, -27.932653665700002]",0.001663,0.0,36.789477,36.789477
17,9.27,"[-79.80758190200001, 67.8364446167]","[-67.8364446167, -79.80758190200001]",0.001694,0.0,104.742701,104.742701
18,9.53,"[-47.884549141200004, -3.9903790951]","[-3.9903790951, 47.884549141200004]",0.002278,0.0,48.050527,48.050527
19,9.80,"[-75.8172028069, 63.8460655216]","[-63.8460655216, -75.8172028069]",0.003140,0.0,99.118960,99.118960
20,10.38,"[-23.942274570600002, 19.951895475500002]","[-19.951895475500002, -23.942274570600002]",0.004818,0.0,31.165857,31.165857
21,10.39,"[-23.942274570600002, 19.951895475500002]","[-19.951895475500002, -23.942274570600002]",0.000621,0.0,31.165857,31.165857
22,11.42,"[-39.903790951000005, -3.9903790951]","[-3.9903790951, 39.903790951000005]",0.000830,0.0,40.102814,40.102814
23,11.81,"[-63.8460655216, 51.8749282363]","[-51.8749282363, -63.8460655216]",0.003277,0.0,82.263772,82.263772
24,12.02,"[-75.8172028069, -7.9807581902]","[-7.9807581902, 75.8172028069]",0.002645,0.0,76.236086,76.236086
25,12.67,"[-19.951895475500002, 15.9615163804]","[-15.9615163804, -19.951895475500002]",0.004630,0.0,25.550893,25.550893
26,12.68,"[-19.951895475500002, 15.9615163804]","[-15.9615163804, -19.951895475500002]",0.000171,0.0,25.550893,25.550893
27,12.69,"[-19.951895475500002, 15.9615163804]","[-15.9615163804, -19.951895475500002]",0.004288,0.0,25.550893,25.550893
28,13.42,"[-67.8364446167, -7.9807581902]","[-7.9807581902, 67.8364446167]",0.000389,0.0,68.304288,68.304288
29,14.25,"[-31.9230327608, -3.9903790951]","[-3.9903790951, 31.9230327608]",0.000018,0.0,32.171465,32.171465
30,14.86,"[-39.903790951000005, -51.8749282363]","[-51.8749282363, 39.903790951000005]",0.003217,0.0,65.447083,65.447083
31,15.19,"[-59.8556864265, -7.9807581902]","[-7.9807581902, 59.8556864265]",0.000752,0.0,60.385393,60.385393
32,16.25,"[-15.9615163804, 11.971137285300001]","[-11.971137285300001, -15.9615163804]",0.003554,0.0,19.951895,19.951895
33,16.26,"[-15.9615163804, 11.971137285300001]","[-11.971137285300001, -15.9615163804]",0.000071,0.0,19.951895,19.951895
34,16.27,"[-11.971137285300001, -15.9615163804]","[-15.9615163804, 11.971137285300001]",0.003411,0.0,19.951895,19.951895
35,17.06,"[-79.80758190200001, -11.971137285300001]","[11.971137285300001, -79.80758190200001]",0.002157,0.0,80.700423,80.700423
36,17.23,"[-75.8172028069, 55.865307331400004]","[-55.865307331400004, -75.8172028069]",0.002131,0.0,94.176328,94.176328
37,17.49,"[-7.9807581902, 51.8749282363]","[-51.8749282363, -7.9807581902]",0.002129,0.0,52.485243,52.485243
38,17.95,"[-43.8941700461, 31.9230327608]","[-31.9230327608, -43.8941700461]",0.004497,0.0,54.275024,54.275024
39,18.92,"[-23.942274570600002, -3.9903790951]","[-3.9903790951, 23.942274570600002]",0.001968,0.0,24.272528,24.272528
40,18.93,"[-23.942274570600002, -3.9903790951]","[-3.9903790951, 23.942274570600002]",0.002269,0.0,24.272528,24.272528
41,20.02,"[-39.903790951000005, 27.932653665700002]","[-27.932653665700002, -39.903790951000005]",0.003435,0.0,48.708784,48.708784
42,20.61,"[-7.9807581902, 43.8941700461]","[-43.8941700461, -7.9807581902]",0.000239,0.0,44.613795,44.613795
43,20.98,"[-63.8460655216, 43.8941700461]","[-43.8941700461, -63.8460655216]",0.003995,0.0,77.479147,77.479147
44,21.24,"[-63.8460655216, -11.971137285300001]","[-11.971137285300001, 63.8460655216]",0.000782,0.0,64.958665,64.958665
45,22.61,"[-11.971137285300001, 7.9807581902]","[-7.9807581902, -11.971137285300001]",0.002477,0.0,14.387516,14.387516
46,22.62,"[-11.971137285300001, 7.9807581902]","[-7.9807581902, -11.971137285300001]",0.000034,0.0,14.387516,14.387516
47,22.63,"[-7.9807581902, -11.971137285300001]","[-11.971137285300001, 7.9807581902]",0.002545,0.0,14.387516,14.387516
48,23.78,"[-75.8172028069, -15.9615163804]","[-15.9615163804, 75.8172028069]",0.003629,0.0,77.479147,77.479147
49,23.95,"[-79.80758190200001, 51.8749282363]","[-51.8749282363, -79.80758190200001]",0.003763,0.0,95.185389,95.185389
50,24.19,"[-55.865307331400004, -11.971137285300001]","[-11.971137285300001, 55.865307331400004]",0.000484,0.0,57.133534,57.133534
51,24.53,"[-55.865307331400004, 35.9134118559]","[-35.9134118559, -55.865307331400004]",0.000525,0.0,66.413144,66.413144
52,25.06,"[-35.9134118559, -7.9807581902]","[-7.9807581902, 35.9134118559]",0.001531,0.0,36.789477,36.789477
53,25.45,"[-75.8172028069, 47.884549141200004]","[-47.884549141200004, -75.8172028069]",0.002017,0.0,89.672617,89.672617
54,25.99,"[-31.9230327608, 19.951895475500002]","[-19.951895475500002, -31.9230327608]",0.000504,0.0,37.645161,37.645161
55,26.48,"[-67.8364446167, -15.9615163804]","[-15.9615163804, 67.8364446167]",0.001265,0.0,69.688975,69.688975
56,27.14,"[-71.8268237118, 43.8941700461]","[-43.8941700461, -71.8268237118]",0.001276,0.0,84.177139,84.177139
57,28.06,"[-15.9615163804, -3.9903790951]","[-3.9903790951, 15.9615163804]",0.003586,0.0,16.452754,16.452754
58,28.07,"[-15.9615163804, -3.9903790951]","[-3.9903790951, 15.9615163804]",0.000714,0.0,16.452754,16.452754
59,28.08,"[-15.9615163804, -3.9903790951]","[-3.9903790951, 15.9615163804]",0.002157,0.0,16.452754,16.452754

In [32]:
tol = 0.05  # Theta‐difference tolerance for “closeness”

# 1) sort by Theta
df_sorted = final_rsdf.sort_values('Theta').reset_index(drop=True)

keep_idxs = []           # indices of the rows we'll keep
current_group = [0]      # start with the first row in group

for i in range(1, len(df_sorted)):
    θ_prev = df_sorted.loc[i-1, 'Theta']
    θ_curr = df_sorted.loc[i,   'Theta']

    if abs(θ_curr - θ_prev) <= tol:
        # same cluster: add to current_group
        current_group.append(i)
    else:
        # new cluster starts: pick best from the old
        best = df_sorted.loc[current_group, 'delvec'].idxmin()
        keep_idxs.append(best)
        current_group = [i]

# final cluster
best = df_sorted.loc[current_group, 'delvec'].idxmin()
keep_idxs.append(best)

# select and restore original order (optional)
result = df_sorted.loc[keep_idxs].sort_index().reset_index(drop=True)

In [34]:
result.head(60)

,Theta,A1,A2,delvec,delang,norm_A1,norm_A2
0,2.94,"[-79.80758190200001, 75.8172028069]","[-75.8172028069, -79.80758190200001]",0.004608,0.0,110.079509,110.079509
1,3.27,"[-71.8268237118, 67.8364446167]","[-67.8364446167, -71.8268237118]",0.005439,0.0,98.797145,98.797145
2,3.47,"[-63.8460655216, -67.8364446167]","[-67.8364446167, 63.8460655216]",0.002291,0.0,93.156338,93.156338
3,3.95,"[-55.865307331400004, -59.8556864265]","[-59.8556864265, 55.865307331400004]",0.000189,0.0,81.875734,81.875734
4,4.24,"[-55.865307331400004, 51.8749282363]","[-51.8749282363, -55.865307331400004]",0.002918,0.0,76.236086,76.236086
5,4.58,"[-51.8749282363, 47.884549141200004]","[-47.884549141200004, -51.8749282363]",0.001503,0.0,70.597013,70.597013
6,4.98,"[-47.884549141200004, 43.8941700461]","[-43.8941700461, -47.884549141200004]",0.001014,0.0,64.958665,64.958665
7,5.45,"[-43.8941700461, 39.903790951000005]","[-39.903790951000005, -43.8941700461]",0.002715,0.0,59.321250,59.321250
8,6.03,"[-39.903790951000005, 35.9134118559]","[-35.9134118559, -39.903790951000005]",0.004146,0.0,53.685060,53.685060
9,6.36,"[-71.8268237118, -3.9903790951]","[-3.9903790951, 71.8268237118]",0.000427,0.0,71.937582,71.937582
10,6.73,"[-35.9134118559, 31.9230327608]","[-31.9230327608, -35.9134118559]",0.002450,0.0,48.050527,48.050527
11,7.15,"[-63.8460655216, -3.9903790951]","[-3.9903790951, 63.8460655216]",0.002980,0.0,63.970643,63.970643
12,7.63,"[-31.9230327608, 27.932653665700002]","[-27.932653665700002, -31.9230327608]",0.001370,0.0,42.418312,42.418312
13,8.17,"[-55.865307331400004, -3.9903790951]","[-3.9903790951, 55.865307331400004]",0.001206,0.0,56.007640,56.007640
14,8.80,"[-27.932653665700002, 23.942274570600002]","[-23.942274570600002, -27.932653665700002]",0.001663,0.0,36.789477,36.789477
15,9.27,"[-79.80758190200001, 67.8364446167]","[-67.8364446167, -79.80758190200001]",0.001694,0.0,104.742701,104.742701
16,9.53,"[-47.884549141200004, -3.9903790951]","[-3.9903790951, 47.884549141200004]",0.002278,0.0,48.050527,48.050527
17,9.80,"[-75.8172028069, 63.8460655216]","[-63.8460655216, -75.8172028069]",0.003140,0.0,99.118960,99.118960
18,10.39,"[-23.942274570600002, 19.951895475500002]","[-19.951895475500002, -23.942274570600002]",0.000621,0.0,31.165857,31.165857
19,11.42,"[-39.903790951000005, -3.9903790951]","[-3.9903790951, 39.903790951000005]",0.000830,0.0,40.102814,40.102814
20,11.81,"[-63.8460655216, 51.8749282363]","[-51.8749282363, -63.8460655216]",0.003277,0.0,82.263772,82.263772
21,12.02,"[-75.8172028069, -7.9807581902]","[-7.9807581902, 75.8172028069]",0.002645,0.0,76.236086,76.236086
22,12.68,"[-19.951895475500002, 15.9615163804]","[-15.9615163804, -19.951895475500002]",0.000171,0.0,25.550893,25.550893
23,13.42,"[-67.8364446167, -7.9807581902]","[-7.9807581902, 67.8364446167]",0.000389,0.0,68.304288,68.304288
24,14.25,"[-31.9230327608, -3.9903790951]","[-3.9903790951, 31.9230327608]",0.000018,0.0,32.171465,32.171465
25,14.86,"[-39.903790951000005, -51.8749282363]","[-51.8749282363, 39.903790951000005]",0.003217,0.0,65.447083,65.447083
26,15.19,"[-59.8556864265, -7.9807581902]","[-7.9807581902, 59.8556864265]",0.000752,0.0,60.385393,60.385393
27,16.26,"[-15.9615163804, 11.971137285300001]","[-11.971137285300001, -15.9615163804]",0.000071,0.0,19.951895,19.951895
28,17.06,"[-79.80758190200001, -11.971137285300001]","[11.971137285300001, -79.80758190200001]",0.002157,0.0,80.700423,80.700423
29,17.23,"[-75.8172028069, 55.865307331400004]","[-55.865307331400004, -75.8172028069]",0.002131,0.0,94.176328,94.176328
30,17.49,"[-7.9807581902, 51.8749282363]","[-51.8749282363, -7.9807581902]",0.002129,0.0,52.485243,52.485243
31,17.95,"[-43.8941700461, 31.9230327608]","[-31.9230327608, -43.8941700461]",0.004497,0.0,54.275024,54.275024
32,18.92,"[-23.942274570600002, -3.9903790951]","[-3.9903790951, 23.942274570600002]",0.001968,0.0,24.272528,24.272528
33,20.02,"[-39.903790951000005, 27.932653665700002]","[-27.932653665700002, -39.903790951000005]",0.003435,0.0,48.708784,48.708784
34,20.61,"[-7.9807581902, 43.8941700461]","[-43.8941700461, -7.9807581902]",0.000239,0.0,44.613795,44.613795
35,20.98,"[-63.8460655216, 43.8941700461]","[-43.8941700461, -63.8460655216]",0.003995,0.0,77.479147,77.479147
36,21.24,"[-63.8460655216, -11.971137285300001]","[-11.971137285300001, 63.8460655216]",0.000782,0.0,64.958665,64.958665
37,22.62,"[-11.971137285300001, 7.9807581902]","[-7.9807581902, -11.971137285300001]",0.000034,0.0,14.387516,14.387516
38,23.78,"[-75.8172028069, -15.9615163804]","[-15.9615163804, 75.8172028069]",0.003629,0.0,77.479147,77.479147
39,23.95,"[-79.80758190200001, 51.8749282363]","[-51.8749282363, -79.80758190200001]",0.003763,0.0,95.185389,95.185389
40,24.19,"[-55.865307331400004, -11.971137285300001]","[-11.971137285300001, 55.865307331400004]",0.000484,0.0,57.133534,57.133534
41,24.53,"[-55.865307331400004, 35.9134118559]","[-35.9134118559, -55.865307331400004]",0.000525,0.0,66.413144,66.413144
42,25.06,"[-35.9134118559, -7.9807581902]","[-7.9807581902, 35.9134118559]",0.001531,0.0,36.789477,36.789477
43,25.45,"[-75.8172028069, 47.884549141200004]","[-47.884549141200004, -75.8172028069]",0.002017,0.0,89.672617,89.672617
44,25.99,"[-31.9230327608, 19.951895475500002]","[-19.951895475500002, -31.9230327608]",0.000504,0.0,37.645161,37.645161
45,26.48,"[-67.8364446167, -15.9615163804]","[-15.9615163804, 67.8364446167]",0.001265,0.0,69.688975,69.688975
46,27.14,"[-71.8268237118, 43.8941700461]","[-43.8941700461, -71.8268237118]",0.001276,0.0,84.177139,84.177139
47,28.07,"[-15.9615163804, -3.9903790951]","[-3.9903790951, 15.9615163804]",0.000714,0.0,16.452754,16.452754
48,29.07,"[-39.903790951000005, -67.8364446167]","[-67.8364446167, 39.903790951000005]",0.001497,0.0,78.702578,78.702578
49,29.49,"[-47.884549141200004, 27.932653665700002]","[-27.932653665700002, -47.884549141200004]",0.002781,0.0,55.436118,55.436118
50,29.86,"[-59.8556864265, -15.9615163804]","[-15.9615163804, 59.8556864265]",0.003064,0.0,61.947342,61.947342
51,30.51,"[-27.932653665700002, 15.9615163804]","[-15.9615163804, -27.932653665700002]",0.000133,0.0,32.171465,32.171465
52,31.05,"[-71.8268237118, -19.951895475500002]","[-19.951895475500002, 71.8268237118]",0.002313,0.0,74.546433,74.546433
53,31.89,"[-7.9807581902, 27.932653665700002]","[-27.932653665700002, -7.9807581902]",0.000401,0.0,29.050398,29.050398
54,32.38,"[-79.80758190200001, 43.8941700461]","[-43.8941700461, -79.80758190200001]",0.002524,0.0,91.082096,91.082096
55,32.78,"[-23.942274570600002, -43.8941700461]","[-43.8941700461, 23.942274570600002]",0.000802,0.0,49.999307,49.999307
56,33.40,"[-11.971137285300001, 39.903790951000005]","[-39.903790951000005, -11.971137285300001]",0.001099,0.0,41.660781,41.660781
57,34.48,"[-75.8172028069, 39.903790951000005]","[-39.903790951000005, -75.8172028069]",0.004365,0.0,85.677073,85.677073
58,34.71,"[-19.951895475500002, 63.8460655216]","[-63.8460655216, -19.951895475500002]",0.002277,0.0,66.890943,66.890943
59,35.05,"[-75.8172028069, -23.942274570600002]","[-23.942274570600002, 75.8172028069]",0.001577,0.0,79.507740,79.507740

In [35]:
result.to_pickle("../moire_structures/bto/bto_bilayer_candidates.pkl")