In [1]:
import MLM.moire_lattice_vector_finder as mlf
import numpy as np
import pandas as pd
import time
import sys, os
from pprint import pprint

sys.path.append("../AtomLayers/refactor")

In [2]:
from match import run_and_filter

In [3]:
file_1 = "/home/anikeya/USC/MLM-v0/moire_structures/PTO_BTO/bto_tetra_monolayer.vasp"
file_2 = "/home/anikeya/USC/MLM-v0/moire_structures/PTO_BTO/pto_tetra_monolayer.vasp"

In [4]:
lattice_vectors1, atom_type_arr1, dat1 = mlf.read_vasp(file_1)

In [5]:
lattice_vectors1['a']

array([3.9903791, 0.       , 0.       ])

In [6]:
lattice_vectors2, atom_type_arr2, dat2 = mlf.read_vasp(file_2)

In [7]:
mlf.angle_between(lattice_vectors1['a'],lattice_vectors1['b'])

90.0

In [25]:
results = run_and_filter(a1=lattice_vectors1['a'][0:2],a2=lattice_vectors1['b'][0:2],
                      g1=lattice_vectors2['a'][0:2],g2=lattice_vectors2['b'][0:2],
                      degmin=1, degmax = 45.01, degstep = 0.01,
                      dtol = 5e-3, nmin = -20, nmax = 20, goodangles = [90.0])

In [27]:
angle=[]
A1 = []
A2 = []
delvec = []
delgood = []
norm_A1 = []
norm_A2 = []
#num_atoms_app = []

for result in results[0]['results']:
    # pprint(len(result))
    # pprint(result)
    # pprint("#################")
    # pprint(result[0]['angle'])
    angle.append(result[0]['angle'])
    # pprint(result[0]['matchpoint'])
    A1.append(result[0]['matchpoint'])
    # pprint(result[1]['matchpoint'])
    A2.append(result[1]['matchpoint'])
    # pprint(result[2]['delgoodangle'])
    delvec.append(result[0]['delvec'])
    delgood.append(np.abs(result[2]['delgoodangle']))
    norm_A1.append(np.linalg.norm(np.array(result[0]['matchpoint'])))
    norm_A2.append(np.linalg.norm(np.array(result[1]['matchpoint'])))
    #num_atoms_app.append(np.abs(density * np.cross(np.array(result[0]['matchpoint']), np.array(result[1]['matchpoint']))))
    
    
    # break

In [28]:
resdf = pd.DataFrame(zip(angle,A1,A2,delvec,delgood,norm_A1, norm_A2), columns=['Theta','A1', 'A2', 'delvec', 'delang','norm_A1', 'norm_A2'])

In [29]:
len(resdf)

1316

In [30]:
# Sort the DataFrame by 'degree' in ascending order and 'norm' in descending order, followed by 'vec_del' and 'delta_angle'
rsdf_sorted = resdf.sort_values(by=['Theta', 'delvec', 'norm_A1'], ascending=[True, True, True])

In [31]:
rsdf_sorted.head(60)

,Theta,A1,A2,delvec,delang,norm_A1,norm_A2
0,2.18,"[-67.8364446167, 47.884549141200004]","[-47.884549141200004, -67.8364446167]",0.014025,0.0,83.034410,83.034410
1,2.18,"[-67.8364446167, 47.884549141200004]","[47.884549141200004, 67.8364446167]",0.014025,0.0,83.034410,83.034410
6,2.18,"[67.8364446167, -47.884549141200004]","[-47.884549141200004, -67.8364446167]",0.014025,0.0,83.034410,83.034410
7,2.18,"[67.8364446167, -47.884549141200004]","[47.884549141200004, 67.8364446167]",0.014025,0.0,83.034410,83.034410
2,2.18,"[-47.884549141200004, -67.8364446167]","[-67.8364446167, 47.884549141200004]",0.014025,0.0,83.034410,83.034410
3,2.18,"[-47.884549141200004, -67.8364446167]","[67.8364446167, -47.884549141200004]",0.014025,0.0,83.034410,83.034410
4,2.18,"[47.884549141200004, 67.8364446167]","[-67.8364446167, 47.884549141200004]",0.014025,0.0,83.034410,83.034410
5,2.18,"[47.884549141200004, 67.8364446167]","[67.8364446167, -47.884549141200004]",0.014025,0.0,83.034410,83.034410
10,2.19,"[-47.884549141200004, -67.8364446167]","[-67.8364446167, 47.884549141200004]",0.008979,0.0,83.034410,83.034410
11,2.19,"[-47.884549141200004, -67.8364446167]","[67.8364446167, -47.884549141200004]",0.008979,0.0,83.034410,83.034410
12,2.19,"[47.884549141200004, 67.8364446167]","[-67.8364446167, 47.884549141200004]",0.008979,0.0,83.034410,83.034410
13,2.19,"[47.884549141200004, 67.8364446167]","[67.8364446167, -47.884549141200004]",0.008979,0.0,83.034410,83.034410
8,2.19,"[-67.8364446167, 47.884549141200004]","[-47.884549141200004, -67.8364446167]",0.008979,0.0,83.034410,83.034410
9,2.19,"[-67.8364446167, 47.884549141200004]","[47.884549141200004, 67.8364446167]",0.008979,0.0,83.034410,83.034410
14,2.19,"[67.8364446167, -47.884549141200004]","[-47.884549141200004, -67.8364446167]",0.008979,0.0,83.034410,83.034410
15,2.19,"[67.8364446167, -47.884549141200004]","[47.884549141200004, 67.8364446167]",0.008979,0.0,83.034410,83.034410
16,2.20,"[-67.8364446167, 47.884549141200004]","[-47.884549141200004, -67.8364446167]",0.019610,0.0,83.034410,83.034410
17,2.20,"[-67.8364446167, 47.884549141200004]","[47.884549141200004, 67.8364446167]",0.019610,0.0,83.034410,83.034410
18,2.20,"[-47.884549141200004, -67.8364446167]","[-67.8364446167, 47.884549141200004]",0.019610,0.0,83.034410,83.034410
19,2.20,"[-47.884549141200004, -67.8364446167]","[67.8364446167, -47.884549141200004]",0.019610,0.0,83.034410,83.034410
20,2.20,"[47.884549141200004, 67.8364446167]","[-67.8364446167, 47.884549141200004]",0.019610,0.0,83.034410,83.034410
21,2.20,"[47.884549141200004, 67.8364446167]","[67.8364446167, -47.884549141200004]",0.019610,0.0,83.034410,83.034410
22,2.20,"[67.8364446167, -47.884549141200004]","[-47.884549141200004, -67.8364446167]",0.019610,0.0,83.034410,83.034410
23,2.20,"[67.8364446167, -47.884549141200004]","[47.884549141200004, 67.8364446167]",0.019610,0.0,83.034410,83.034410
24,5.89,"[-35.9134118559, 7.9807581902]","[-7.9807581902, -35.9134118559]",0.018385,0.0,36.789477,36.789477
25,5.89,"[-35.9134118559, 7.9807581902]","[7.9807581902, 35.9134118559]",0.018385,0.0,36.789477,36.789477
30,5.89,"[35.9134118559, -7.9807581902]","[-7.9807581902, -35.9134118559]",0.018385,0.0,36.789477,36.789477
31,5.89,"[35.9134118559, -7.9807581902]","[7.9807581902, 35.9134118559]",0.018385,0.0,36.789477,36.789477
26,5.89,"[-7.9807581902, -35.9134118559]","[-35.9134118559, 7.9807581902]",0.018385,0.0,36.789477,36.789477
27,5.89,"[-7.9807581902, -35.9134118559]","[35.9134118559, -7.9807581902]",0.018385,0.0,36.789477,36.789477
28,5.89,"[7.9807581902, 35.9134118559]","[-35.9134118559, 7.9807581902]",0.018385,0.0,36.789477,36.789477
29,5.89,"[7.9807581902, 35.9134118559]","[35.9134118559, -7.9807581902]",0.018385,0.0,36.789477,36.789477
32,5.90,"[-35.9134118559, 7.9807581902]","[-7.9807581902, -35.9134118559]",0.015687,0.0,36.789477,36.789477
33,5.90,"[-35.9134118559, 7.9807581902]","[7.9807581902, 35.9134118559]",0.015687,0.0,36.789477,36.789477
34,5.90,"[-7.9807581902, -35.9134118559]","[-35.9134118559, 7.9807581902]",0.015687,0.0,36.789477,36.789477
35,5.90,"[-7.9807581902, -35.9134118559]","[35.9134118559, -7.9807581902]",0.015687,0.0,36.789477,36.789477
36,5.90,"[7.9807581902, 35.9134118559]","[-35.9134118559, 7.9807581902]",0.015687,0.0,36.789477,36.789477
37,5.90,"[7.9807581902, 35.9134118559]","[35.9134118559, -7.9807581902]",0.015687,0.0,36.789477,36.789477
38,5.90,"[35.9134118559, -7.9807581902]","[-7.9807581902, -35.9134118559]",0.015687,0.0,36.789477,36.789477
39,5.90,"[35.9134118559, -7.9807581902]","[7.9807581902, 35.9134118559]",0.015687,0.0,36.789477,36.789477
40,5.91,"[-35.9134118559, 7.9807581902]","[-7.9807581902, -35.9134118559]",0.015384,0.0,36.789477,36.789477
41,5.91,"[-35.9134118559, 7.9807581902]","[7.9807581902, 35.9134118559]",0.015384,0.0,36.789477,36.789477
42,5.91,"[-7.9807581902, -35.9134118559]","[-35.9134118559, 7.9807581902]",0.015384,0.0,36.789477,36.789477
43,5.91,"[-7.9807581902, -35.9134118559]","[35.9134118559, -7.9807581902]",0.015384,0.0,36.789477,36.789477
44,5.91,"[7.9807581902, 35.9134118559]","[-35.9134118559, 7.9807581902]",0.015384,0.0,36.789477,36.789477
45,5.91,"[7.9807581902, 35.9134118559]","[35.9134118559, -7.9807581902]",0.015384,0.0,36.789477,36.789477
46,5.91,"[35.9134118559, -7.9807581902]","[-7.9807581902, -35.9134118559]",0.015384,0.0,36.789477,36.789477
47,5.91,"[35.9134118559, -7.9807581902]","[7.9807581902, 35.9134118559]",0.015384,0.0,36.789477,36.789477
50,5.91,"[-27.932653665700002, 43.8941700461]","[-43.8941700461, -27.932653665700002]",0.021757,0.0,52.028178,52.028178
51,5.91,"[-27.932653665700002, 43.8941700461]","[43.8941700461, 27.932653665700002]",0.021757,0.0,52.028178,52.028178
52,5.91,"[27.932653665700002, -43.8941700461]","[-43.8941700461, -27.932653665700002]",0.021757,0.0,52.028178,52.028178
53,5.91,"[27.932653665700002, -43.8941700461]","[43.8941700461, 27.932653665700002]",0.021757,0.0,52.028178,52.028178
48,5.91,"[-43.8941700461, -27.932653665700002]","[-27.932653665700002, 43.8941700461]",0.021757,0.0,52.028178,52.028178
49,5.91,"[-43.8941700461, -27.932653665700002]","[27.932653665700002, -43.8941700461]",0.021757,0.0,52.028178,52.028178
54,5.91,"[43.8941700461, 27.932653665700002]","[-27.932653665700002, 43.8941700461]",0.021757,0.0,52.028178,52.028178
55,5.91,"[43.8941700461, 27.932653665700002]","[27.932653665700002, -43.8941700461]",0.021757,0.0,52.028178,52.028178
56,5.92,"[-35.9134118559, 7.9807581902]","[-7.9807581902, -35.9134118559]",0.017600,0.0,36.789477,36.789477
57,5.92,"[-35.9134118559, 7.9807581902]","[7.9807581902, 35.9134118559]",0.017600,0.0,36.789477,36.789477
62,5.92,"[35.9134118559, -7.9807581902]","[-7.9807581902, -35.9134118559]",0.017600,0.0,36.789477,36.789477
63,5.92,"[35.9134118559, -7.9807581902]","[7.9807581902, 35.9134118559]",0.017600,0.0,36.789477,36.789477

In [32]:
# Group by 'degree' and take the first entry in each group
final_rsdf = rsdf_sorted.groupby('Theta', as_index=False).first()

In [33]:
len(final_rsdf)

103

In [34]:
# final_rsdf['num_atoms'] = np.round(1.574158*final_rsdf['norm_A1']*final_rsdf['norm_A2'])

In [35]:
final_rsdf.sort_values(by="delvec", ascending=True).head(60)

,Theta,A1,A2,delvec,delang,norm_A1,norm_A2
102,45.00,"[-43.8941700461, -43.8941700461]","[-43.8941700461, 43.8941700461]",0.002900,0.0,62.075731,62.075731
76,30.96,"[-3.9903790951, -15.9615163804]","[-15.9615163804, 3.9903790951]",0.006875,0.0,16.452754,16.452754
77,30.97,"[-15.9615163804, 3.9903790951]","[-3.9903790951, -15.9615163804]",0.007023,0.0,16.452754,16.452754
75,30.95,"[-3.9903790951, -15.9615163804]","[-15.9615163804, 3.9903790951]",0.007856,0.0,16.452754,16.452754
58,26.03,"[-35.9134118559, 55.865307331400004]","[-55.865307331400004, -35.9134118559]",0.007970,0.0,66.413144,66.413144
61,26.57,"[-79.80758190200001, -39.903790951000005]","[39.903790951000005, -79.80758190200001]",0.007989,0.0,89.227589,89.227589
60,26.56,"[-79.80758190200001, -39.903790951000005]","[39.903790951000005, -79.80758190200001]",0.008143,0.0,89.227589,89.227589
95,39.45,"[-35.9134118559, 55.865307331400004]","[-55.865307331400004, -35.9134118559]",0.008228,0.0,66.413144,66.413144
78,30.98,"[-15.9615163804, 3.9903790951]","[-3.9903790951, -15.9615163804]",0.008239,0.0,16.452754,16.452754
94,39.44,"[-55.865307331400004, -35.9134118559]","[-35.9134118559, 55.865307331400004]",0.008330,0.0,66.413144,66.413144
57,26.02,"[-35.9134118559, 55.865307331400004]","[-55.865307331400004, -35.9134118559]",0.008601,0.0,66.413144,66.413144
1,2.19,"[-47.884549141200004, -67.8364446167]","[-67.8364446167, 47.884549141200004]",0.008979,0.0,83.034410,83.034410
28,17.38,"[-67.8364446167, 47.884549141200004]","[-47.884549141200004, -67.8364446167]",0.009402,0.0,83.034410,83.034410
74,30.94,"[-15.9615163804, 3.9903790951]","[-3.9903790951, -15.9615163804]",0.009626,0.0,16.452754,16.452754
99,40.36,"[-79.80758190200001, -67.8364446167]","[67.8364446167, -79.80758190200001]",0.009789,0.0,104.742701,104.742701
40,21.65,"[-43.8941700461, 15.9615163804]","[-15.9615163804, -43.8941700461]",0.009808,0.0,46.706190,46.706190
24,15.22,"[-43.8941700461, -15.9615163804]","[-15.9615163804, 43.8941700461]",0.009811,0.0,46.706190,46.706190
79,30.99,"[-3.9903790951, -15.9615163804]","[-15.9615163804, 3.9903790951]",0.010145,0.0,16.452754,16.452754
53,24.75,"[-43.8941700461, -15.9615163804]","[-15.9615163804, 43.8941700461]",0.010153,0.0,46.706190,46.706190
65,28.38,"[-15.9615163804, -43.8941700461]","[-43.8941700461, 15.9615163804]",0.010176,0.0,46.706190,46.706190
66,28.39,"[-43.8941700461, 15.9615163804]","[-15.9615163804, -43.8941700461]",0.011199,0.0,46.706190,46.706190
69,30.35,"[-63.8460655216, -59.8556864265]","[-59.8556864265, 63.8460655216]",0.011207,0.0,87.515846,87.515846
101,44.99,"[-43.8941700461, -43.8941700461]","[-43.8941700461, 43.8941700461]",0.011215,0.0,62.075731,62.075731
52,24.74,"[-43.8941700461, -15.9615163804]","[-15.9615163804, 43.8941700461]",0.011240,0.0,46.706190,46.706190
100,40.37,"[-79.80758190200001, -67.8364446167]","[67.8364446167, -79.80758190200001]",0.011261,0.0,104.742701,104.742701
91,37.03,"[-79.80758190200001, -35.9134118559]","[35.9134118559, -79.80758190200001]",0.011262,0.0,87.515846,87.515846
73,30.93,"[-3.9903790951, -15.9615163804]","[-15.9615163804, 3.9903790951]",0.011837,0.0,16.452754,16.452754
89,34.04,"[-59.8556864265, -63.8460655216]","[-63.8460655216, 59.8556864265]",0.011978,0.0,87.515846,87.515846
18,11.42,"[-79.80758190200001, -35.9134118559]","[35.9134118559, -79.80758190200001]",0.012068,0.0,87.515846,87.515846
80,31.00,"[-15.9615163804, 3.9903790951]","[-3.9903790951, -15.9615163804]",0.012429,0.0,16.452754,16.452754
23,15.21,"[-43.8941700461, -15.9615163804]","[-15.9615163804, 43.8941700461]",0.012474,0.0,46.706190,46.706190
41,21.66,"[-43.8941700461, 15.9615163804]","[-15.9615163804, -43.8941700461]",0.012526,0.0,46.706190,46.706190
14,10.46,"[-63.8460655216, 3.9903790951]","[-3.9903790951, -63.8460655216]",0.012566,0.0,63.970643,63.970643
31,17.61,"[-63.8460655216, -3.9903790951]","[-3.9903790951, 63.8460655216]",0.012891,0.0,63.970643,63.970643
39,21.64,"[-15.9615163804, -43.8941700461]","[-43.8941700461, 15.9615163804]",0.012977,0.0,46.706190,46.706190
25,15.23,"[-43.8941700461, -15.9615163804]","[-15.9615163804, 43.8941700461]",0.013032,0.0,46.706190,46.706190
27,17.37,"[-67.8364446167, 47.884549141200004]","[-47.884549141200004, -67.8364446167]",0.013210,0.0,83.034410,83.034410
0,2.18,"[-67.8364446167, 47.884549141200004]","[-47.884549141200004, -67.8364446167]",0.014025,0.0,83.034410,83.034410
72,30.92,"[-3.9903790951, -15.9615163804]","[-15.9615163804, 3.9903790951]",0.014285,0.0,16.452754,16.452754
54,24.76,"[-43.8941700461, -15.9615163804]","[-15.9615163804, 43.8941700461]",0.014587,0.0,46.706190,46.706190
64,28.37,"[-15.9615163804, -43.8941700461]","[-43.8941700461, 15.9615163804]",0.014649,0.0,46.706190,46.706190
19,11.43,"[-79.80758190200001, -35.9134118559]","[35.9134118559, -79.80758190200001]",0.014717,0.0,87.515846,87.515846
90,34.05,"[-63.8460655216, 59.8556864265]","[-59.8556864265, -63.8460655216]",0.014858,0.0,87.515846,87.515846
81,31.01,"[-15.9615163804, 3.9903790951]","[-3.9903790951, -15.9615163804]",0.014917,0.0,16.452754,16.452754
32,17.62,"[-63.8460655216, -3.9903790951]","[-3.9903790951, 63.8460655216]",0.015053,0.0,63.970643,63.970643
86,32.38,"[-55.865307331400004, 51.8749282363]","[-51.8749282363, -55.865307331400004]",0.015340,0.0,76.236086,76.236086
45,22.17,"[-27.932653665700002, -23.942274570600002]","[-23.942274570600002, 27.932653665700002]",0.015364,0.0,36.789477,36.789477
36,20.75,"[-7.9807581902, 75.8172028069]","[-75.8172028069, -7.9807581902]",0.015369,0.0,76.236086,76.236086
5,5.91,"[-35.9134118559, 7.9807581902]","[-7.9807581902, -35.9134118559]",0.015384,0.0,36.789477,36.789477
4,5.90,"[-35.9134118559, 7.9807581902]","[-7.9807581902, -35.9134118559]",0.015687,0.0,36.789477,36.789477
44,22.16,"[-27.932653665700002, -23.942274570600002]","[-23.942274570600002, 27.932653665700002]",0.015721,0.0,36.789477,36.789477
10,8.73,"[-75.8172028069, 7.9807581902]","[-7.9807581902, -75.8172028069]",0.016164,0.0,76.236086,76.236086
63,28.14,"[-55.865307331400004, -51.8749282363]","[-51.8749282363, 55.865307331400004]",0.016216,0.0,76.236086,76.236086
92,37.04,"[-79.80758190200001, -35.9134118559]","[35.9134118559, -79.80758190200001]",0.016319,0.0,87.515846,87.515846
68,30.34,"[-63.8460655216, -59.8556864265]","[-59.8556864265, 63.8460655216]",0.016473,0.0,87.515846,87.515846
62,28.13,"[-51.8749282363, 55.865307331400004]","[-55.865307331400004, -51.8749282363]",0.016584,0.0,76.236086,76.236086
11,8.74,"[-75.8172028069, 7.9807581902]","[-7.9807581902, -75.8172028069]",0.016643,0.0,76.236086,76.236086
67,28.40,"[-43.8941700461, 15.9615163804]","[-15.9615163804, -43.8941700461]",0.016740,0.0,46.706190,46.706190
13,10.45,"[-63.8460655216, 3.9903790951]","[-3.9903790951, -63.8460655216]",0.016743,0.0,63.970643,63.970643
51,24.73,"[-15.9615163804, 43.8941700461]","[-43.8941700461, -15.9615163804]",0.016808,0.0,46.706190,46.706190

In [36]:
tol = 0.05  # Theta‐difference tolerance for “closeness”

# 1) sort by Theta
df_sorted = final_rsdf.sort_values('Theta').reset_index(drop=True)

keep_idxs = []           # indices of the rows we'll keep
current_group = [0]      # start with the first row in group

for i in range(1, len(df_sorted)):
    θ_prev = df_sorted.loc[i-1, 'Theta']
    θ_curr = df_sorted.loc[i,   'Theta']

    if abs(θ_curr - θ_prev) <= tol:
        # same cluster: add to current_group
        current_group.append(i)
    else:
        # new cluster starts: pick best from the old
        best = df_sorted.loc[current_group, 'delvec'].idxmin()
        keep_idxs.append(best)
        current_group = [i]

# final cluster
best = df_sorted.loc[current_group, 'delvec'].idxmin()
keep_idxs.append(best)

# select and restore original order (optional)
result = df_sorted.loc[keep_idxs].sort_index().reset_index(drop=True)

In [41]:
result.sort_values(by="Theta", ascending=True).head(60)

,Theta,A1,A2,delvec,delang,norm_A1,norm_A2
0,2.19,"[-47.884549141200004, -67.8364446167]","[-67.8364446167, 47.884549141200004]",0.008979,0.0,83.034410,83.034410
1,5.91,"[-35.9134118559, 7.9807581902]","[-7.9807581902, -35.9134118559]",0.015384,0.0,36.789477,36.789477
2,7.17,"[-55.865307331400004, 39.903790951000005]","[-39.903790951000005, -55.865307331400004]",0.016923,0.0,68.653078,68.653078
3,8.73,"[-75.8172028069, 7.9807581902]","[-7.9807581902, -75.8172028069]",0.016164,0.0,76.236086,76.236086
4,9.52,"[-75.8172028069, -63.8460655216]","[-63.8460655216, 75.8172028069]",0.018810,0.0,99.118960,99.118960
5,10.46,"[-63.8460655216, 3.9903790951]","[-3.9903790951, -63.8460655216]",0.012566,0.0,63.970643,63.970643
6,11.42,"[-79.80758190200001, -35.9134118559]","[35.9134118559, -79.80758190200001]",0.012068,0.0,87.515846,87.515846
7,11.75,"[-55.865307331400004, 39.903790951000005]","[-39.903790951000005, -55.865307331400004]",0.017162,0.0,68.653078,68.653078
8,15.22,"[-43.8941700461, -15.9615163804]","[-15.9615163804, 43.8941700461]",0.009811,0.0,46.706190,46.706190
9,17.38,"[-67.8364446167, 47.884549141200004]","[-47.884549141200004, -67.8364446167]",0.009402,0.0,83.034410,83.034410
10,17.61,"[-63.8460655216, -3.9903790951]","[-3.9903790951, 63.8460655216]",0.012891,0.0,63.970643,63.970643
11,19.32,"[-75.8172028069, 63.8460655216]","[-63.8460655216, -75.8172028069]",0.018585,0.0,99.118960,99.118960
12,20.75,"[-7.9807581902, 75.8172028069]","[-75.8172028069, -7.9807581902]",0.015369,0.0,76.236086,76.236086
13,21.65,"[-43.8941700461, 15.9615163804]","[-15.9615163804, -43.8941700461]",0.009808,0.0,46.706190,46.706190
14,22.17,"[-27.932653665700002, -23.942274570600002]","[-23.942274570600002, 27.932653665700002]",0.015364,0.0,36.789477,36.789477
15,23.14,"[-71.8268237118, 19.951895475500002]","[-19.951895475500002, -71.8268237118]",0.023356,0.0,74.546433,74.546433
16,23.37,"[-79.80758190200001, -59.8556864265]","[59.8556864265, -79.80758190200001]",0.018029,0.0,99.759477,99.759477
17,24.75,"[-43.8941700461, -15.9615163804]","[-15.9615163804, 43.8941700461]",0.010153,0.0,46.706190,46.706190
18,26.03,"[-35.9134118559, 55.865307331400004]","[-55.865307331400004, -35.9134118559]",0.007970,0.0,66.413144,66.413144
19,26.57,"[-79.80758190200001, -39.903790951000005]","[39.903790951000005, -79.80758190200001]",0.007989,0.0,89.227589,89.227589
20,28.14,"[-55.865307331400004, -51.8749282363]","[-51.8749282363, 55.865307331400004]",0.016216,0.0,76.236086,76.236086
21,28.38,"[-15.9615163804, -43.8941700461]","[-43.8941700461, 15.9615163804]",0.010176,0.0,46.706190,46.706190
22,30.35,"[-63.8460655216, -59.8556864265]","[-59.8556864265, 63.8460655216]",0.011207,0.0,87.515846,87.515846
23,30.96,"[-3.9903790951, -15.9615163804]","[-15.9615163804, 3.9903790951]",0.006875,0.0,16.452754,16.452754
24,31.92,"[-79.80758190200001, -3.9903790951]","[3.9903790951, -79.80758190200001]",0.022801,0.0,79.907279,79.907279
25,32.38,"[-55.865307331400004, 51.8749282363]","[-51.8749282363, -55.865307331400004]",0.015340,0.0,76.236086,76.236086
26,34.04,"[-59.8556864265, -63.8460655216]","[-63.8460655216, 59.8556864265]",0.011978,0.0,87.515846,87.515846
27,37.03,"[-79.80758190200001, -35.9134118559]","[35.9134118559, -79.80758190200001]",0.011262,0.0,87.515846,87.515846
28,39.45,"[-35.9134118559, 55.865307331400004]","[-55.865307331400004, -35.9134118559]",0.008228,0.0,66.413144,66.413144
29,39.63,"[-59.8556864265, -79.80758190200001]","[-79.80758190200001, 59.8556864265]",0.018176,0.0,99.759477,99.759477
30,40.36,"[-79.80758190200001, -67.8364446167]","[67.8364446167, -79.80758190200001]",0.009789,0.0,104.742701,104.742701
31,45.00,"[-43.8941700461, -43.8941700461]","[-43.8941700461, 43.8941700461]",0.002900,0.0,62.075731,62.075731

In [38]:
result.to_pickle("../moire_structures/PTO_BTO/PTO_BTO_bilayer_tetra_candidates.pkl")

In [39]:
len(result)

32