In [1]:
import MLM.moire_lattice_vector_finder as mlf
import numpy as np
import pandas as pd
import time

In [2]:
file_1 = "../moire_structures/bto/bto_1-layer.vasp"
file_2 = "../moire_structures/bto/bto_1-layer.vasp"

In [3]:
lattice_vectors1, atom_type_arr1, dat1 = mlf.read_vasp(file_1)

In [4]:
lattice_vectors2, atom_type_arr2, dat2 = mlf.read_vasp(file_2)

In [5]:
mlf.angle_between(lattice_vectors1['a'],lattice_vectors1['b'])

90.0

In [6]:
import multiprocessing 
multiprocessing.cpu_count()

20

In [7]:
start = time.time()
test = mlf.find_index(a1=lattice_vectors1['a'],a2=lattice_vectors1['b'],a3=lattice_vectors1['c'],
                    b1=lattice_vectors2['a'],b2=lattice_vectors2['b'],b3=lattice_vectors2['c'],
                    theta_min=22.4,theta_max=22.8,theta_step=0.01,
                    n_min = 1, n_max=20,
                    dtol = 0.01, ang_lat = 90.0, num_cores=16)
end = time.time()
print(f"Time taken: {end-start} secs")

Time taken: 3.0562644004821777 secs

In [8]:
# Define the column names
columns = ['degree', 'n1', 'n2', 'n1p', 'n2p','vec_del', 'delta_angle', 'norm','A1','A2']
df = pd.DataFrame(test, columns=columns)
len(df)

976

In [9]:
# Sort the DataFrame by 'degree' in ascending order and 'norm' in descending order, followed by 'vec_del' and 'delta_angle'
df_sorted = df.sort_values(by=['degree', 'norm', 'vec_del', 'delta_angle','n1','n2'], ascending=[True, True, True, True, False, False])

In [10]:
df_sorted.head()

,degree,n1,n2,n1p,n2p,vec_del,delta_angle,norm,A1,A2
6,22.59,3,-2,-2,-3,0.007499,0.0,20.347021,"[11.971137285300001, -7.9807581902, 0.0]","[-7.9807581902, -11.971137285300001, -0.0]"
7,22.59,3,-2,2,3,0.007499,0.0,20.347021,"[11.971137285300001, -7.9807581902, 0.0]","[7.9807581902, 11.971137285300001, 0.0]"
4,22.59,2,3,-3,2,0.007499,0.0,20.347021,"[7.9807581902, 11.971137285300001, 0.0]","[-11.971137285300001, 7.9807581902, 0.0]"
5,22.59,2,3,3,-2,0.007499,0.0,20.347021,"[7.9807581902, 11.971137285300001, 0.0]","[11.971137285300001, -7.9807581902, 0.0]"
2,22.59,-2,-3,-3,2,0.007499,0.0,20.347021,"[-7.9807581902, -11.971137285300001, -0.0]","[-11.971137285300001, 7.9807581902, 0.0]"

In [11]:
# Group by 'degree' and take the first entry in each group
final_df = df_sorted.groupby('degree', as_index=False).first()

In [12]:
len(final_df)

7

In [14]:
final_df.sort_values(by=['vec_del'])

,degree,n1,n2,n1p,n2p,vec_del,delta_angle,norm,A1,A2
3,22.62,3,-2,-2,-3,0.000034,0.0,20.347021,"[11.971137285300001, -7.9807581902, 0.0]","[-7.9807581902, -11.971137285300001, -0.0]"
2,22.61,3,-2,-2,-3,0.002477,0.0,20.347021,"[11.971137285300001, -7.9807581902, 0.0]","[-7.9807581902, -11.971137285300001, -0.0]"
4,22.63,3,-2,-2,-3,0.002545,0.0,20.347021,"[11.971137285300001, -7.9807581902, 0.0]","[-7.9807581902, -11.971137285300001, -0.0]"
1,22.60,3,-2,-2,-3,0.004988,0.0,20.347021,"[11.971137285300001, -7.9807581902, 0.0]","[-7.9807581902, -11.971137285300001, -0.0]"
5,22.64,3,-2,-2,-3,0.005056,0.0,20.347021,"[11.971137285300001, -7.9807581902, 0.0]","[-7.9807581902, -11.971137285300001, -0.0]"
0,22.59,3,-2,-2,-3,0.007499,0.0,20.347021,"[11.971137285300001, -7.9807581902, 0.0]","[-7.9807581902, -11.971137285300001, -0.0]"
6,22.65,3,-2,-2,-3,0.007567,0.0,20.347021,"[11.971137285300001, -7.9807581902, 0.0]","[-7.9807581902, -11.971137285300001, -0.0]"

In [15]:
final_df.to_csv('../moire_structures/bto/bto_bilayer_candidates.csv')

In [16]:
final_df.to_pickle('../moire_structures/bto/bto_bilayer_candidates.pkl')

# Third layer Doamin

In [17]:
file_3 = "../moire_structures/bto/bto_1-layer.vasp"

In [18]:
lattice_vectors3, atom_type_arr3, dat3 = mlf.read_vasp(file_3)

In [19]:
lattice_vectors3

{'a': array([3.9903791, 0.       , 0.       ]),
 'b': array([0.       , 3.9903791, 0.       ]),
 'c': array([0.        , 0.        , 8.20531082])}

In [20]:
for i,row in final_df.iterrows():
    if i == 3:
        
        print(i)
        print(f"Degree: {row['degree']}")
        moire_vector_a = np.array(row['A1'])
        moire_vector_b = np.array(row['A2'])
        moire_vector_c = np.array([0.0,0.0,1.0])
        print(f"Moire Vector A: {moire_vector_a}")
        print(f"Moire Vector B: {moire_vector_b}")
        print(f"Moire Vector C: {moire_vector_c}")
        print(f"Lattice Vector A: {lattice_vectors3['a']}")
        print(f"Lattice Vector B: {lattice_vectors3['b']}")
        print(f"Lattice Vector C: {lattice_vectors3['c']}")
        test2 = mlf.find_index(a1=moire_vector_a,a2=moire_vector_b,a3=moire_vector_c,
                        b1=lattice_vectors3['a'],b2=lattice_vectors3['b'],b3=lattice_vectors3['c'],
                        theta_min=36.7,theta_max=36.9,theta_step=0.01,
                        n_min = 1, n_max=40,dtol = 0.01, ang_lat = 90.0,num_cores=16)
        
        break

3
Degree: 22.620000000000033
Moire Vector A: [11.97113729 -7.98075819  0.        ]
Moire Vector B: [ -7.98075819 -11.97113729  -0.        ]
Moire Vector C: [0. 0. 1.]
Lattice Vector A: [3.9903791 0.        0.       ]
Lattice Vector B: [0.        3.9903791 0.       ]
Lattice Vector C: [0.         0.         8.20531082]

In [21]:
# Define the column names
columns = ['degree', 'n1', 'n2', 'n1p', 'n2p','vec_del', 'delta_angle', 'norm','A1','A2']
df = pd.DataFrame(test2, columns=columns)
len(df)

488

In [22]:
df_sorted = df.sort_values(by=['degree', 'norm','vec_del', 'delta_angle'])

In [23]:
# Group by 'degree' and take the first entry in each group
final2_df = df_sorted.groupby('degree', as_index=False).first()
len(final2_df)

3

In [24]:
final2_df['theta']=22.62

In [26]:
final2_df.sort_values(by=['vec_del'])

,degree,n1,n2,n1p,n2p,vec_del,delta_angle,norm,A1,A2,theta
1,36.87,-2,-1,-1,2,0.000057,0.0,45.497322,"[-15.961516380400003, 27.932653665700002, 0.0]","[-27.932653665700002, -15.961516380400003, -0.0]",22.62
0,36.86,-2,-1,-1,2,0.005558,0.0,45.497322,"[-15.961516380400003, 27.932653665700002, 0.0]","[-27.932653665700002, -15.961516380400003, -0.0]",22.62
2,36.88,-2,-1,-1,2,0.005672,0.0,45.497322,"[-15.961516380400003, 27.932653665700002, 0.0]","[-27.932653665700002, -15.961516380400003, -0.0]",22.62

In [27]:
final2_df.to_csv('../moire_structures/bto/bto_trilayer_candidates_22.62.csv')

In [28]:
final2_df.to_pickle('../moire_structures/bto/bto_trilayer_candidates_22.62.pkl')